/**
 * generated by Xtext 2.14.0
 */
package se.cth.generator;

import org.eclipse.xtend2.lib.StringConcatenation;
import se.cth.generator.set_of_actions;

@SuppressWarnings("all")
public class state {
  public set_of_actions azioni_permesse;
  
  public String ID;
  
  public state(final String name) {
    set_of_actions _set_of_actions = new set_of_actions();
    this.azioni_permesse = _set_of_actions;
    this.ID = name;
  }
  
  public void add_action(final String action) {
    int i = 0;
    boolean flag = true;
    while ((i < this.azioni_permesse.size())) {
      {
        boolean _is_there = this.azioni_permesse.is_there(action);
        if (_is_there) {
          flag = false;
        }
        i++;
      }
    }
    if (flag) {
      this.azioni_permesse.add_action(action);
    }
  }
  
  public boolean isEmpty() {
    return this.azioni_permesse.isEmpty();
  }
  
  public CharSequence print_state() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("azioni in ");
    _builder.append(this.ID);
    _builder.append(":");
    CharSequence _print_all = this.azioni_permesse.print_all();
    _builder.append(_print_all);
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  public boolean is_there(final String str) {
    return this.azioni_permesse.is_there(str);
  }
}
