/*
 * generated by Xtext 2.17.0.M1
 */
package it.polimi


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class PuRSUEMLRuntimeModule extends AbstractPuRSUEMLRuntimeModule {
}
