/*
 * generated by Xtext 2.17.0.M1
 */
package it.polimi.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class PuRSUEMLUiModule extends AbstractPuRSUEMLUiModule {
}
