/*
 * generated by Xtext 2.14.0
 */
package se.cth


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class PursueStandaloneSetup extends PursueStandaloneSetupGenerated {

	def static void doSetup() {
		new PursueStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
