/*
 * generated by Xtext 2.17.0.M1
 */
package it.polimi.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPuRSUEMLScopeProvider extends DelegatingScopeProvider {
}
