/*
 * generated by Xtext 2.17.0.M1
 */
package it.polimi.parser.antlr;

import com.google.inject.Inject;
import it.polimi.parser.antlr.internal.InternalPuRSUEMLParser;
import it.polimi.services.PuRSUEMLGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class PuRSUEMLParser extends AbstractAntlrParser {

	@Inject
	private PuRSUEMLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalPuRSUEMLParser createParser(XtextTokenStream stream) {
		return new InternalPuRSUEMLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "PuRSUEML";
	}

	public PuRSUEMLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PuRSUEMLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
