/**
 * generated by Xtext 2.14.0
 */
package it.polimi.generator;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class strin {
  public String ga;
  
  public void update(final String str) {
    this.ga = str;
  }
  
  public boolean is_equal(final String str) {
    return this.ga.equals(str);
  }
  
  public strin(final String str) {
    this.ga = str;
  }
}
