/**
 * generated by Xtext 2.14.0
 */
package se.cth.pursue;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Agent</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link se.cth.pursue.Agent#getName <em>Name</em>}</li>
 *   <li>{@link se.cth.pursue.Agent#isControllable <em>Controllable</em>}</li>
 *   <li>{@link se.cth.pursue.Agent#isMobile <em>Mobile</em>}</li>
 *   <li>{@link se.cth.pursue.Agent#getSpeed <em>Speed</em>}</li>
 *   <li>{@link se.cth.pursue.Agent#getInitial_location <em>Initial location</em>}</li>
 *   <li>{@link se.cth.pursue.Agent#getActions <em>Actions</em>}</li>
 *   <li>{@link se.cth.pursue.Agent#getReactions <em>Reactions</em>}</li>
 * </ul>
 *
 * @see se.cth.pursue.PursuePackage#getAgent()
 * @model
 * @generated
 */
public interface Agent extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see se.cth.pursue.PursuePackage#getAgent_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link se.cth.pursue.Agent#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Controllable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Controllable</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Controllable</em>' attribute.
   * @see #setControllable(boolean)
   * @see se.cth.pursue.PursuePackage#getAgent_Controllable()
   * @model
   * @generated
   */
  boolean isControllable();

  /**
   * Sets the value of the '{@link se.cth.pursue.Agent#isControllable <em>Controllable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Controllable</em>' attribute.
   * @see #isControllable()
   * @generated
   */
  void setControllable(boolean value);

  /**
   * Returns the value of the '<em><b>Mobile</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Mobile</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mobile</em>' attribute.
   * @see #setMobile(boolean)
   * @see se.cth.pursue.PursuePackage#getAgent_Mobile()
   * @model
   * @generated
   */
  boolean isMobile();

  /**
   * Sets the value of the '{@link se.cth.pursue.Agent#isMobile <em>Mobile</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mobile</em>' attribute.
   * @see #isMobile()
   * @generated
   */
  void setMobile(boolean value);

  /**
   * Returns the value of the '<em><b>Speed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Speed</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Speed</em>' attribute.
   * @see #setSpeed(int)
   * @see se.cth.pursue.PursuePackage#getAgent_Speed()
   * @model
   * @generated
   */
  int getSpeed();

  /**
   * Sets the value of the '{@link se.cth.pursue.Agent#getSpeed <em>Speed</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Speed</em>' attribute.
   * @see #getSpeed()
   * @generated
   */
  void setSpeed(int value);

  /**
   * Returns the value of the '<em><b>Initial location</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Initial location</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Initial location</em>' reference.
   * @see #setInitial_location(Pdi)
   * @see se.cth.pursue.PursuePackage#getAgent_Initial_location()
   * @model
   * @generated
   */
  Pdi getInitial_location();

  /**
   * Sets the value of the '{@link se.cth.pursue.Agent#getInitial_location <em>Initial location</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Initial location</em>' reference.
   * @see #getInitial_location()
   * @generated
   */
  void setInitial_location(Pdi value);

  /**
   * Returns the value of the '<em><b>Actions</b></em>' reference list.
   * The list contents are of type {@link se.cth.pursue.Event}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Actions</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actions</em>' reference list.
   * @see se.cth.pursue.PursuePackage#getAgent_Actions()
   * @model
   * @generated
   */
  EList<Event> getActions();

  /**
   * Returns the value of the '<em><b>Reactions</b></em>' reference list.
   * The list contents are of type {@link se.cth.pursue.Event}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Reactions</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reactions</em>' reference list.
   * @see se.cth.pursue.PursuePackage#getAgent_Reactions()
   * @model
   * @generated
   */
  EList<Event> getReactions();

} // Agent
