/**
 * generated by Xtext 2.14.0
 */
package se.cth.pursue;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>connection</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link se.cth.pursue.connection#getPdi1 <em>Pdi1</em>}</li>
 *   <li>{@link se.cth.pursue.connection#getPdi2 <em>Pdi2</em>}</li>
 *   <li>{@link se.cth.pursue.connection#getDistance <em>Distance</em>}</li>
 * </ul>
 *
 * @see se.cth.pursue.PursuePackage#getconnection()
 * @model
 * @generated
 */
public interface connection extends EObject
{
  /**
   * Returns the value of the '<em><b>Pdi1</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pdi1</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pdi1</em>' reference.
   * @see #setPdi1(Pdi)
   * @see se.cth.pursue.PursuePackage#getconnection_Pdi1()
   * @model
   * @generated
   */
  Pdi getPdi1();

  /**
   * Sets the value of the '{@link se.cth.pursue.connection#getPdi1 <em>Pdi1</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pdi1</em>' reference.
   * @see #getPdi1()
   * @generated
   */
  void setPdi1(Pdi value);

  /**
   * Returns the value of the '<em><b>Pdi2</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pdi2</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pdi2</em>' reference.
   * @see #setPdi2(Pdi)
   * @see se.cth.pursue.PursuePackage#getconnection_Pdi2()
   * @model
   * @generated
   */
  Pdi getPdi2();

  /**
   * Sets the value of the '{@link se.cth.pursue.connection#getPdi2 <em>Pdi2</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pdi2</em>' reference.
   * @see #getPdi2()
   * @generated
   */
  void setPdi2(Pdi value);

  /**
   * Returns the value of the '<em><b>Distance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Distance</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Distance</em>' attribute.
   * @see #setDistance(int)
   * @see se.cth.pursue.PursuePackage#getconnection_Distance()
   * @model
   * @generated
   */
  int getDistance();

  /**
   * Sets the value of the '{@link se.cth.pursue.connection#getDistance <em>Distance</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Distance</em>' attribute.
   * @see #getDistance()
   * @generated
   */
  void setDistance(int value);

} // connection
