/**
 * generated by Xtext 2.14.0
 */
package se.cth.pursue;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Event</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link se.cth.pursue.Event#getName <em>Name</em>}</li>
 *   <li>{@link se.cth.pursue.Event#isCollaborative <em>Collaborative</em>}</li>
 *   <li>{@link se.cth.pursue.Event#isLocation_specific <em>Location specific</em>}</li>
 *   <li>{@link se.cth.pursue.Event#getLocation <em>Location</em>}</li>
 *   <li>{@link se.cth.pursue.Event#isHas_duration <em>Has duration</em>}</li>
 *   <li>{@link se.cth.pursue.Event#getDuration <em>Duration</em>}</li>
 * </ul>
 *
 * @see se.cth.pursue.PursuePackage#getEvent()
 * @model
 * @generated
 */
public interface Event extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see se.cth.pursue.PursuePackage#getEvent_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link se.cth.pursue.Event#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Collaborative</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Collaborative</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Collaborative</em>' attribute.
   * @see #setCollaborative(boolean)
   * @see se.cth.pursue.PursuePackage#getEvent_Collaborative()
   * @model
   * @generated
   */
  boolean isCollaborative();

  /**
   * Sets the value of the '{@link se.cth.pursue.Event#isCollaborative <em>Collaborative</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Collaborative</em>' attribute.
   * @see #isCollaborative()
   * @generated
   */
  void setCollaborative(boolean value);

  /**
   * Returns the value of the '<em><b>Location specific</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Location specific</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Location specific</em>' attribute.
   * @see #setLocation_specific(boolean)
   * @see se.cth.pursue.PursuePackage#getEvent_Location_specific()
   * @model
   * @generated
   */
  boolean isLocation_specific();

  /**
   * Sets the value of the '{@link se.cth.pursue.Event#isLocation_specific <em>Location specific</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Location specific</em>' attribute.
   * @see #isLocation_specific()
   * @generated
   */
  void setLocation_specific(boolean value);

  /**
   * Returns the value of the '<em><b>Location</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Location</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Location</em>' reference.
   * @see #setLocation(Pdi)
   * @see se.cth.pursue.PursuePackage#getEvent_Location()
   * @model
   * @generated
   */
  Pdi getLocation();

  /**
   * Sets the value of the '{@link se.cth.pursue.Event#getLocation <em>Location</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Location</em>' reference.
   * @see #getLocation()
   * @generated
   */
  void setLocation(Pdi value);

  /**
   * Returns the value of the '<em><b>Has duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Has duration</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Has duration</em>' attribute.
   * @see #setHas_duration(boolean)
   * @see se.cth.pursue.PursuePackage#getEvent_Has_duration()
   * @model
   * @generated
   */
  boolean isHas_duration();

  /**
   * Sets the value of the '{@link se.cth.pursue.Event#isHas_duration <em>Has duration</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Has duration</em>' attribute.
   * @see #isHas_duration()
   * @generated
   */
  void setHas_duration(boolean value);

  /**
   * Returns the value of the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Duration</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Duration</em>' attribute.
   * @see #setDuration(int)
   * @see se.cth.pursue.PursuePackage#getEvent_Duration()
   * @model
   * @generated
   */
  int getDuration();

  /**
   * Sets the value of the '{@link se.cth.pursue.Event#getDuration <em>Duration</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Duration</em>' attribute.
   * @see #getDuration()
   * @generated
   */
  void setDuration(int value);

} // Event
