/**
 * generated by Xtext 2.14.0
 */
package se.cth.pursue;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link se.cth.pursue.Model#getLocations <em>Locations</em>}</li>
 *   <li>{@link se.cth.pursue.Model#getConnections <em>Connections</em>}</li>
 *   <li>{@link se.cth.pursue.Model#getEvents <em>Events</em>}</li>
 *   <li>{@link se.cth.pursue.Model#getRegole <em>Regole</em>}</li>
 *   <li>{@link se.cth.pursue.Model#getStati <em>Stati</em>}</li>
 *   <li>{@link se.cth.pursue.Model#getDipendenze <em>Dipendenze</em>}</li>
 *   <li>{@link se.cth.pursue.Model#getAgents <em>Agents</em>}</li>
 *   <li>{@link se.cth.pursue.Model#isHave_obj <em>Have obj</em>}</li>
 *   <li>{@link se.cth.pursue.Model#getObjective <em>Objective</em>}</li>
 *   <li>{@link se.cth.pursue.Model#isHave_reach_obj <em>Have reach obj</em>}</li>
 *   <li>{@link se.cth.pursue.Model#getReachobjective <em>Reachobjective</em>}</li>
 * </ul>
 *
 * @see se.cth.pursue.PursuePackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Locations</b></em>' containment reference list.
   * The list contents are of type {@link se.cth.pursue.Pdi}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Locations</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Locations</em>' containment reference list.
   * @see se.cth.pursue.PursuePackage#getModel_Locations()
   * @model containment="true"
   * @generated
   */
  EList<Pdi> getLocations();

  /**
   * Returns the value of the '<em><b>Connections</b></em>' containment reference list.
   * The list contents are of type {@link se.cth.pursue.connection}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Connections</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Connections</em>' containment reference list.
   * @see se.cth.pursue.PursuePackage#getModel_Connections()
   * @model containment="true"
   * @generated
   */
  EList<connection> getConnections();

  /**
   * Returns the value of the '<em><b>Events</b></em>' containment reference list.
   * The list contents are of type {@link se.cth.pursue.Event}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Events</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Events</em>' containment reference list.
   * @see se.cth.pursue.PursuePackage#getModel_Events()
   * @model containment="true"
   * @generated
   */
  EList<Event> getEvents();

  /**
   * Returns the value of the '<em><b>Regole</b></em>' containment reference list.
   * The list contents are of type {@link se.cth.pursue.Regola}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Regole</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Regole</em>' containment reference list.
   * @see se.cth.pursue.PursuePackage#getModel_Regole()
   * @model containment="true"
   * @generated
   */
  EList<Regola> getRegole();

  /**
   * Returns the value of the '<em><b>Stati</b></em>' containment reference list.
   * The list contents are of type {@link se.cth.pursue.Stato}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Stati</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stati</em>' containment reference list.
   * @see se.cth.pursue.PursuePackage#getModel_Stati()
   * @model containment="true"
   * @generated
   */
  EList<Stato> getStati();

  /**
   * Returns the value of the '<em><b>Dipendenze</b></em>' containment reference list.
   * The list contents are of type {@link se.cth.pursue.StateDep}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dipendenze</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dipendenze</em>' containment reference list.
   * @see se.cth.pursue.PursuePackage#getModel_Dipendenze()
   * @model containment="true"
   * @generated
   */
  EList<StateDep> getDipendenze();

  /**
   * Returns the value of the '<em><b>Agents</b></em>' containment reference list.
   * The list contents are of type {@link se.cth.pursue.Agent}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Agents</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Agents</em>' containment reference list.
   * @see se.cth.pursue.PursuePackage#getModel_Agents()
   * @model containment="true"
   * @generated
   */
  EList<Agent> getAgents();

  /**
   * Returns the value of the '<em><b>Have obj</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Have obj</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Have obj</em>' attribute.
   * @see #setHave_obj(boolean)
   * @see se.cth.pursue.PursuePackage#getModel_Have_obj()
   * @model
   * @generated
   */
  boolean isHave_obj();

  /**
   * Sets the value of the '{@link se.cth.pursue.Model#isHave_obj <em>Have obj</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Have obj</em>' attribute.
   * @see #isHave_obj()
   * @generated
   */
  void setHave_obj(boolean value);

  /**
   * Returns the value of the '<em><b>Objective</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Objective</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objective</em>' containment reference.
   * @see #setObjective(Objective)
   * @see se.cth.pursue.PursuePackage#getModel_Objective()
   * @model containment="true"
   * @generated
   */
  Objective getObjective();

  /**
   * Sets the value of the '{@link se.cth.pursue.Model#getObjective <em>Objective</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Objective</em>' containment reference.
   * @see #getObjective()
   * @generated
   */
  void setObjective(Objective value);

  /**
   * Returns the value of the '<em><b>Have reach obj</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Have reach obj</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Have reach obj</em>' attribute.
   * @see #setHave_reach_obj(boolean)
   * @see se.cth.pursue.PursuePackage#getModel_Have_reach_obj()
   * @model
   * @generated
   */
  boolean isHave_reach_obj();

  /**
   * Sets the value of the '{@link se.cth.pursue.Model#isHave_reach_obj <em>Have reach obj</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Have reach obj</em>' attribute.
   * @see #isHave_reach_obj()
   * @generated
   */
  void setHave_reach_obj(boolean value);

  /**
   * Returns the value of the '<em><b>Reachobjective</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Reachobjective</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reachobjective</em>' containment reference.
   * @see #setReachobjective(ReachObjective)
   * @see se.cth.pursue.PursuePackage#getModel_Reachobjective()
   * @model containment="true"
   * @generated
   */
  ReachObjective getReachobjective();

  /**
   * Sets the value of the '{@link se.cth.pursue.Model#getReachobjective <em>Reachobjective</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reachobjective</em>' containment reference.
   * @see #getReachobjective()
   * @generated
   */
  void setReachobjective(ReachObjective value);

} // Model
