/**
 * generated by Xtext 2.14.0
 */
package se.cth.pursue;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Objective</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link se.cth.pursue.Objective#isIs_if <em>Is if</em>}</li>
 *   <li>{@link se.cth.pursue.Objective#getCause <em>Cause</em>}</li>
 *   <li>{@link se.cth.pursue.Objective#getReaction <em>Reaction</em>}</li>
 *   <li>{@link se.cth.pursue.Objective#getTime <em>Time</em>}</li>
 *   <li>{@link se.cth.pursue.Objective#isIs_avoid <em>Is avoid</em>}</li>
 *   <li>{@link se.cth.pursue.Objective#getLose <em>Lose</em>}</li>
 * </ul>
 *
 * @see se.cth.pursue.PursuePackage#getObjective()
 * @model
 * @generated
 */
public interface Objective extends EObject
{
  /**
   * Returns the value of the '<em><b>Is if</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is if</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is if</em>' attribute.
   * @see #setIs_if(boolean)
   * @see se.cth.pursue.PursuePackage#getObjective_Is_if()
   * @model
   * @generated
   */
  boolean isIs_if();

  /**
   * Sets the value of the '{@link se.cth.pursue.Objective#isIs_if <em>Is if</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is if</em>' attribute.
   * @see #isIs_if()
   * @generated
   */
  void setIs_if(boolean value);

  /**
   * Returns the value of the '<em><b>Cause</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cause</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cause</em>' reference.
   * @see #setCause(Event)
   * @see se.cth.pursue.PursuePackage#getObjective_Cause()
   * @model
   * @generated
   */
  Event getCause();

  /**
   * Sets the value of the '{@link se.cth.pursue.Objective#getCause <em>Cause</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cause</em>' reference.
   * @see #getCause()
   * @generated
   */
  void setCause(Event value);

  /**
   * Returns the value of the '<em><b>Reaction</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Reaction</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reaction</em>' reference.
   * @see #setReaction(Event)
   * @see se.cth.pursue.PursuePackage#getObjective_Reaction()
   * @model
   * @generated
   */
  Event getReaction();

  /**
   * Sets the value of the '{@link se.cth.pursue.Objective#getReaction <em>Reaction</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reaction</em>' reference.
   * @see #getReaction()
   * @generated
   */
  void setReaction(Event value);

  /**
   * Returns the value of the '<em><b>Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Time</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Time</em>' attribute.
   * @see #setTime(int)
   * @see se.cth.pursue.PursuePackage#getObjective_Time()
   * @model
   * @generated
   */
  int getTime();

  /**
   * Sets the value of the '{@link se.cth.pursue.Objective#getTime <em>Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Time</em>' attribute.
   * @see #getTime()
   * @generated
   */
  void setTime(int value);

  /**
   * Returns the value of the '<em><b>Is avoid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is avoid</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is avoid</em>' attribute.
   * @see #setIs_avoid(boolean)
   * @see se.cth.pursue.PursuePackage#getObjective_Is_avoid()
   * @model
   * @generated
   */
  boolean isIs_avoid();

  /**
   * Sets the value of the '{@link se.cth.pursue.Objective#isIs_avoid <em>Is avoid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is avoid</em>' attribute.
   * @see #isIs_avoid()
   * @generated
   */
  void setIs_avoid(boolean value);

  /**
   * Returns the value of the '<em><b>Lose</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Lose</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lose</em>' reference.
   * @see #setLose(Event)
   * @see se.cth.pursue.PursuePackage#getObjective_Lose()
   * @model
   * @generated
   */
  Event getLose();

  /**
   * Sets the value of the '{@link se.cth.pursue.Objective#getLose <em>Lose</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lose</em>' reference.
   * @see #getLose()
   * @generated
   */
  void setLose(Event value);

} // Objective
