/**
 * generated by Xtext 2.14.0
 */
package se.cth.pursue;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sequence</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link se.cth.pursue.Sequence#getFirst_ev <em>First ev</em>}</li>
 *   <li>{@link se.cth.pursue.Sequence#isIs_seq1 <em>Is seq1</em>}</li>
 *   <li>{@link se.cth.pursue.Sequence#getFirst_seq <em>First seq</em>}</li>
 *   <li>{@link se.cth.pursue.Sequence#isThen <em>Then</em>}</li>
 *   <li>{@link se.cth.pursue.Sequence#isOr <em>Or</em>}</li>
 *   <li>{@link se.cth.pursue.Sequence#getSecond_ev <em>Second ev</em>}</li>
 *   <li>{@link se.cth.pursue.Sequence#isIs_seq2 <em>Is seq2</em>}</li>
 *   <li>{@link se.cth.pursue.Sequence#getSecond_seq <em>Second seq</em>}</li>
 * </ul>
 *
 * @see se.cth.pursue.PursuePackage#getSequence()
 * @model
 * @generated
 */
public interface Sequence extends EObject
{
  /**
   * Returns the value of the '<em><b>First ev</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>First ev</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>First ev</em>' reference.
   * @see #setFirst_ev(Event)
   * @see se.cth.pursue.PursuePackage#getSequence_First_ev()
   * @model
   * @generated
   */
  Event getFirst_ev();

  /**
   * Sets the value of the '{@link se.cth.pursue.Sequence#getFirst_ev <em>First ev</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>First ev</em>' reference.
   * @see #getFirst_ev()
   * @generated
   */
  void setFirst_ev(Event value);

  /**
   * Returns the value of the '<em><b>Is seq1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is seq1</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is seq1</em>' attribute.
   * @see #setIs_seq1(boolean)
   * @see se.cth.pursue.PursuePackage#getSequence_Is_seq1()
   * @model
   * @generated
   */
  boolean isIs_seq1();

  /**
   * Sets the value of the '{@link se.cth.pursue.Sequence#isIs_seq1 <em>Is seq1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is seq1</em>' attribute.
   * @see #isIs_seq1()
   * @generated
   */
  void setIs_seq1(boolean value);

  /**
   * Returns the value of the '<em><b>First seq</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>First seq</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>First seq</em>' containment reference.
   * @see #setFirst_seq(Sequence)
   * @see se.cth.pursue.PursuePackage#getSequence_First_seq()
   * @model containment="true"
   * @generated
   */
  Sequence getFirst_seq();

  /**
   * Sets the value of the '{@link se.cth.pursue.Sequence#getFirst_seq <em>First seq</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>First seq</em>' containment reference.
   * @see #getFirst_seq()
   * @generated
   */
  void setFirst_seq(Sequence value);

  /**
   * Returns the value of the '<em><b>Then</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Then</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Then</em>' attribute.
   * @see #setThen(boolean)
   * @see se.cth.pursue.PursuePackage#getSequence_Then()
   * @model
   * @generated
   */
  boolean isThen();

  /**
   * Sets the value of the '{@link se.cth.pursue.Sequence#isThen <em>Then</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Then</em>' attribute.
   * @see #isThen()
   * @generated
   */
  void setThen(boolean value);

  /**
   * Returns the value of the '<em><b>Or</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Or</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Or</em>' attribute.
   * @see #setOr(boolean)
   * @see se.cth.pursue.PursuePackage#getSequence_Or()
   * @model
   * @generated
   */
  boolean isOr();

  /**
   * Sets the value of the '{@link se.cth.pursue.Sequence#isOr <em>Or</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Or</em>' attribute.
   * @see #isOr()
   * @generated
   */
  void setOr(boolean value);

  /**
   * Returns the value of the '<em><b>Second ev</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Second ev</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Second ev</em>' reference.
   * @see #setSecond_ev(Event)
   * @see se.cth.pursue.PursuePackage#getSequence_Second_ev()
   * @model
   * @generated
   */
  Event getSecond_ev();

  /**
   * Sets the value of the '{@link se.cth.pursue.Sequence#getSecond_ev <em>Second ev</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Second ev</em>' reference.
   * @see #getSecond_ev()
   * @generated
   */
  void setSecond_ev(Event value);

  /**
   * Returns the value of the '<em><b>Is seq2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is seq2</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is seq2</em>' attribute.
   * @see #setIs_seq2(boolean)
   * @see se.cth.pursue.PursuePackage#getSequence_Is_seq2()
   * @model
   * @generated
   */
  boolean isIs_seq2();

  /**
   * Sets the value of the '{@link se.cth.pursue.Sequence#isIs_seq2 <em>Is seq2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is seq2</em>' attribute.
   * @see #isIs_seq2()
   * @generated
   */
  void setIs_seq2(boolean value);

  /**
   * Returns the value of the '<em><b>Second seq</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Second seq</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Second seq</em>' containment reference.
   * @see #setSecond_seq(Sequence)
   * @see se.cth.pursue.PursuePackage#getSequence_Second_seq()
   * @model containment="true"
   * @generated
   */
  Sequence getSecond_seq();

  /**
   * Sets the value of the '{@link se.cth.pursue.Sequence#getSecond_seq <em>Second seq</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Second seq</em>' containment reference.
   * @see #getSecond_seq()
   * @generated
   */
  void setSecond_seq(Sequence value);

} // Sequence
