/**
 * generated by Xtext 2.14.0
 */
package se.cth.pursue;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Stato</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link se.cth.pursue.Stato#getName <em>Name</em>}</li>
 *   <li>{@link se.cth.pursue.Stato#isTr <em>Tr</em>}</li>
 *   <li>{@link se.cth.pursue.Stato#isFl <em>Fl</em>}</li>
 *   <li>{@link se.cth.pursue.Stato#getTrue_events <em>True events</em>}</li>
 *   <li>{@link se.cth.pursue.Stato#getFalse_events <em>False events</em>}</li>
 * </ul>
 *
 * @see se.cth.pursue.PursuePackage#getStato()
 * @model
 * @generated
 */
public interface Stato extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see se.cth.pursue.PursuePackage#getStato_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link se.cth.pursue.Stato#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Tr</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tr</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tr</em>' attribute.
   * @see #setTr(boolean)
   * @see se.cth.pursue.PursuePackage#getStato_Tr()
   * @model
   * @generated
   */
  boolean isTr();

  /**
   * Sets the value of the '{@link se.cth.pursue.Stato#isTr <em>Tr</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tr</em>' attribute.
   * @see #isTr()
   * @generated
   */
  void setTr(boolean value);

  /**
   * Returns the value of the '<em><b>Fl</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fl</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fl</em>' attribute.
   * @see #setFl(boolean)
   * @see se.cth.pursue.PursuePackage#getStato_Fl()
   * @model
   * @generated
   */
  boolean isFl();

  /**
   * Sets the value of the '{@link se.cth.pursue.Stato#isFl <em>Fl</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fl</em>' attribute.
   * @see #isFl()
   * @generated
   */
  void setFl(boolean value);

  /**
   * Returns the value of the '<em><b>True events</b></em>' reference list.
   * The list contents are of type {@link se.cth.pursue.Event}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>True events</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>True events</em>' reference list.
   * @see se.cth.pursue.PursuePackage#getStato_True_events()
   * @model
   * @generated
   */
  EList<Event> getTrue_events();

  /**
   * Returns the value of the '<em><b>False events</b></em>' reference list.
   * The list contents are of type {@link se.cth.pursue.Event}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>False events</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>False events</em>' reference list.
   * @see se.cth.pursue.PursuePackage#getStato_False_events()
   * @model
   * @generated
   */
  EList<Event> getFalse_events();

} // Stato
