/**
 * generated by Xtext 2.17.0.M1
 */
package it.polimi.pursueml.impl;

import it.polimi.pursueml.Event;
import it.polimi.pursueml.Objective;
import it.polimi.pursueml.PursuemlPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Objective</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link it.polimi.pursueml.impl.ObjectiveImpl#isIs_if <em>Is if</em>}</li>
 *   <li>{@link it.polimi.pursueml.impl.ObjectiveImpl#getCause <em>Cause</em>}</li>
 *   <li>{@link it.polimi.pursueml.impl.ObjectiveImpl#getReaction <em>Reaction</em>}</li>
 *   <li>{@link it.polimi.pursueml.impl.ObjectiveImpl#getTime <em>Time</em>}</li>
 *   <li>{@link it.polimi.pursueml.impl.ObjectiveImpl#isIs_avoid <em>Is avoid</em>}</li>
 *   <li>{@link it.polimi.pursueml.impl.ObjectiveImpl#getLose <em>Lose</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ObjectiveImpl extends MinimalEObjectImpl.Container implements Objective
{
  /**
   * The default value of the '{@link #isIs_if() <em>Is if</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIs_if()
   * @generated
   * @ordered
   */
  protected static final boolean IS_IF_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isIs_if() <em>Is if</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIs_if()
   * @generated
   * @ordered
   */
  protected boolean is_if = IS_IF_EDEFAULT;

  /**
   * The cached value of the '{@link #getCause() <em>Cause</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCause()
   * @generated
   * @ordered
   */
  protected Event cause;

  /**
   * The cached value of the '{@link #getReaction() <em>Reaction</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReaction()
   * @generated
   * @ordered
   */
  protected Event reaction;

  /**
   * The default value of the '{@link #getTime() <em>Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTime()
   * @generated
   * @ordered
   */
  protected static final int TIME_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getTime() <em>Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTime()
   * @generated
   * @ordered
   */
  protected int time = TIME_EDEFAULT;

  /**
   * The default value of the '{@link #isIs_avoid() <em>Is avoid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIs_avoid()
   * @generated
   * @ordered
   */
  protected static final boolean IS_AVOID_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isIs_avoid() <em>Is avoid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIs_avoid()
   * @generated
   * @ordered
   */
  protected boolean is_avoid = IS_AVOID_EDEFAULT;

  /**
   * The cached value of the '{@link #getLose() <em>Lose</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLose()
   * @generated
   * @ordered
   */
  protected Event lose;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ObjectiveImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PursuemlPackage.Literals.OBJECTIVE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isIs_if()
  {
    return is_if;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIs_if(boolean newIs_if)
  {
    boolean oldIs_if = is_if;
    is_if = newIs_if;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PursuemlPackage.OBJECTIVE__IS_IF, oldIs_if, is_if));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Event getCause()
  {
    if (cause != null && cause.eIsProxy())
    {
      InternalEObject oldCause = (InternalEObject)cause;
      cause = (Event)eResolveProxy(oldCause);
      if (cause != oldCause)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, PursuemlPackage.OBJECTIVE__CAUSE, oldCause, cause));
      }
    }
    return cause;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Event basicGetCause()
  {
    return cause;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCause(Event newCause)
  {
    Event oldCause = cause;
    cause = newCause;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PursuemlPackage.OBJECTIVE__CAUSE, oldCause, cause));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Event getReaction()
  {
    if (reaction != null && reaction.eIsProxy())
    {
      InternalEObject oldReaction = (InternalEObject)reaction;
      reaction = (Event)eResolveProxy(oldReaction);
      if (reaction != oldReaction)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, PursuemlPackage.OBJECTIVE__REACTION, oldReaction, reaction));
      }
    }
    return reaction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Event basicGetReaction()
  {
    return reaction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setReaction(Event newReaction)
  {
    Event oldReaction = reaction;
    reaction = newReaction;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PursuemlPackage.OBJECTIVE__REACTION, oldReaction, reaction));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getTime()
  {
    return time;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTime(int newTime)
  {
    int oldTime = time;
    time = newTime;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PursuemlPackage.OBJECTIVE__TIME, oldTime, time));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isIs_avoid()
  {
    return is_avoid;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIs_avoid(boolean newIs_avoid)
  {
    boolean oldIs_avoid = is_avoid;
    is_avoid = newIs_avoid;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PursuemlPackage.OBJECTIVE__IS_AVOID, oldIs_avoid, is_avoid));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Event getLose()
  {
    if (lose != null && lose.eIsProxy())
    {
      InternalEObject oldLose = (InternalEObject)lose;
      lose = (Event)eResolveProxy(oldLose);
      if (lose != oldLose)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, PursuemlPackage.OBJECTIVE__LOSE, oldLose, lose));
      }
    }
    return lose;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Event basicGetLose()
  {
    return lose;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLose(Event newLose)
  {
    Event oldLose = lose;
    lose = newLose;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PursuemlPackage.OBJECTIVE__LOSE, oldLose, lose));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PursuemlPackage.OBJECTIVE__IS_IF:
        return isIs_if();
      case PursuemlPackage.OBJECTIVE__CAUSE:
        if (resolve) return getCause();
        return basicGetCause();
      case PursuemlPackage.OBJECTIVE__REACTION:
        if (resolve) return getReaction();
        return basicGetReaction();
      case PursuemlPackage.OBJECTIVE__TIME:
        return getTime();
      case PursuemlPackage.OBJECTIVE__IS_AVOID:
        return isIs_avoid();
      case PursuemlPackage.OBJECTIVE__LOSE:
        if (resolve) return getLose();
        return basicGetLose();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PursuemlPackage.OBJECTIVE__IS_IF:
        setIs_if((Boolean)newValue);
        return;
      case PursuemlPackage.OBJECTIVE__CAUSE:
        setCause((Event)newValue);
        return;
      case PursuemlPackage.OBJECTIVE__REACTION:
        setReaction((Event)newValue);
        return;
      case PursuemlPackage.OBJECTIVE__TIME:
        setTime((Integer)newValue);
        return;
      case PursuemlPackage.OBJECTIVE__IS_AVOID:
        setIs_avoid((Boolean)newValue);
        return;
      case PursuemlPackage.OBJECTIVE__LOSE:
        setLose((Event)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PursuemlPackage.OBJECTIVE__IS_IF:
        setIs_if(IS_IF_EDEFAULT);
        return;
      case PursuemlPackage.OBJECTIVE__CAUSE:
        setCause((Event)null);
        return;
      case PursuemlPackage.OBJECTIVE__REACTION:
        setReaction((Event)null);
        return;
      case PursuemlPackage.OBJECTIVE__TIME:
        setTime(TIME_EDEFAULT);
        return;
      case PursuemlPackage.OBJECTIVE__IS_AVOID:
        setIs_avoid(IS_AVOID_EDEFAULT);
        return;
      case PursuemlPackage.OBJECTIVE__LOSE:
        setLose((Event)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PursuemlPackage.OBJECTIVE__IS_IF:
        return is_if != IS_IF_EDEFAULT;
      case PursuemlPackage.OBJECTIVE__CAUSE:
        return cause != null;
      case PursuemlPackage.OBJECTIVE__REACTION:
        return reaction != null;
      case PursuemlPackage.OBJECTIVE__TIME:
        return time != TIME_EDEFAULT;
      case PursuemlPackage.OBJECTIVE__IS_AVOID:
        return is_avoid != IS_AVOID_EDEFAULT;
      case PursuemlPackage.OBJECTIVE__LOSE:
        return lose != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (is_if: ");
    result.append(is_if);
    result.append(", time: ");
    result.append(time);
    result.append(", is_avoid: ");
    result.append(is_avoid);
    result.append(')');
    return result.toString();
  }

} //ObjectiveImpl
