/**
 * generated by Xtext 2.17.0.M1
 */
package it.polimi.pursueml.impl;

import it.polimi.pursueml.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class PursuemlFactoryImpl extends EFactoryImpl implements PursuemlFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static PursuemlFactory init()
  {
    try
    {
      PursuemlFactory thePursuemlFactory = (PursuemlFactory)EPackage.Registry.INSTANCE.getEFactory(PursuemlPackage.eNS_URI);
      if (thePursuemlFactory != null)
      {
        return thePursuemlFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new PursuemlFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PursuemlFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case PursuemlPackage.PU_RSUEML: return createPuRSUEML();
      case PursuemlPackage.PDI: return createPdi();
      case PursuemlPackage.CONNECTION: return createconnection();
      case PursuemlPackage.EVENT: return createEvent();
      case PursuemlPackage.REGOLA: return createRegola();
      case PursuemlPackage.SEQUENCE: return createSequence();
      case PursuemlPackage.STATO: return createStato();
      case PursuemlPackage.STATE_DEP: return createStateDep();
      case PursuemlPackage.AGENT: return createAgent();
      case PursuemlPackage.OBJECTIVE: return createObjective();
      case PursuemlPackage.REACH_OBJECTIVE: return createReachObjective();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PuRSUEML createPuRSUEML()
  {
    PuRSUEMLImpl puRSUEML = new PuRSUEMLImpl();
    return puRSUEML;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Pdi createPdi()
  {
    PdiImpl pdi = new PdiImpl();
    return pdi;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public connection createconnection()
  {
    connectionImpl connection = new connectionImpl();
    return connection;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Event createEvent()
  {
    EventImpl event = new EventImpl();
    return event;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Regola createRegola()
  {
    RegolaImpl regola = new RegolaImpl();
    return regola;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Sequence createSequence()
  {
    SequenceImpl sequence = new SequenceImpl();
    return sequence;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Stato createStato()
  {
    StatoImpl stato = new StatoImpl();
    return stato;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public StateDep createStateDep()
  {
    StateDepImpl stateDep = new StateDepImpl();
    return stateDep;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Agent createAgent()
  {
    AgentImpl agent = new AgentImpl();
    return agent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Objective createObjective()
  {
    ObjectiveImpl objective = new ObjectiveImpl();
    return objective;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ReachObjective createReachObjective()
  {
    ReachObjectiveImpl reachObjective = new ReachObjectiveImpl();
    return reachObjective;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PursuemlPackage getPursuemlPackage()
  {
    return (PursuemlPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static PursuemlPackage getPackage()
  {
    return PursuemlPackage.eINSTANCE;
  }

} //PursuemlFactoryImpl
