/**
 * generated by Xtext 2.17.0.M1
 */
package it.polimi.pursueml.impl;

import it.polimi.pursueml.Agent;
import it.polimi.pursueml.Event;
import it.polimi.pursueml.Objective;
import it.polimi.pursueml.Pdi;
import it.polimi.pursueml.PuRSUEML;
import it.polimi.pursueml.PursuemlPackage;
import it.polimi.pursueml.ReachObjective;
import it.polimi.pursueml.Regola;
import it.polimi.pursueml.StateDep;
import it.polimi.pursueml.Stato;
import it.polimi.pursueml.connection;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Pu RSUEML</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link it.polimi.pursueml.impl.PuRSUEMLImpl#getLocations <em>Locations</em>}</li>
 *   <li>{@link it.polimi.pursueml.impl.PuRSUEMLImpl#getConnections <em>Connections</em>}</li>
 *   <li>{@link it.polimi.pursueml.impl.PuRSUEMLImpl#getEvents <em>Events</em>}</li>
 *   <li>{@link it.polimi.pursueml.impl.PuRSUEMLImpl#getRegole <em>Regole</em>}</li>
 *   <li>{@link it.polimi.pursueml.impl.PuRSUEMLImpl#getStati <em>Stati</em>}</li>
 *   <li>{@link it.polimi.pursueml.impl.PuRSUEMLImpl#getDipendenze <em>Dipendenze</em>}</li>
 *   <li>{@link it.polimi.pursueml.impl.PuRSUEMLImpl#getAgents <em>Agents</em>}</li>
 *   <li>{@link it.polimi.pursueml.impl.PuRSUEMLImpl#isHave_obj <em>Have obj</em>}</li>
 *   <li>{@link it.polimi.pursueml.impl.PuRSUEMLImpl#getObjective <em>Objective</em>}</li>
 *   <li>{@link it.polimi.pursueml.impl.PuRSUEMLImpl#isHave_reach_obj <em>Have reach obj</em>}</li>
 *   <li>{@link it.polimi.pursueml.impl.PuRSUEMLImpl#getReachobjective <em>Reachobjective</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PuRSUEMLImpl extends MinimalEObjectImpl.Container implements PuRSUEML
{
  /**
   * The cached value of the '{@link #getLocations() <em>Locations</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLocations()
   * @generated
   * @ordered
   */
  protected EList<Pdi> locations;

  /**
   * The cached value of the '{@link #getConnections() <em>Connections</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConnections()
   * @generated
   * @ordered
   */
  protected EList<connection> connections;

  /**
   * The cached value of the '{@link #getEvents() <em>Events</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEvents()
   * @generated
   * @ordered
   */
  protected EList<Event> events;

  /**
   * The cached value of the '{@link #getRegole() <em>Regole</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRegole()
   * @generated
   * @ordered
   */
  protected EList<Regola> regole;

  /**
   * The cached value of the '{@link #getStati() <em>Stati</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStati()
   * @generated
   * @ordered
   */
  protected EList<Stato> stati;

  /**
   * The cached value of the '{@link #getDipendenze() <em>Dipendenze</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDipendenze()
   * @generated
   * @ordered
   */
  protected EList<StateDep> dipendenze;

  /**
   * The cached value of the '{@link #getAgents() <em>Agents</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAgents()
   * @generated
   * @ordered
   */
  protected EList<Agent> agents;

  /**
   * The default value of the '{@link #isHave_obj() <em>Have obj</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isHave_obj()
   * @generated
   * @ordered
   */
  protected static final boolean HAVE_OBJ_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isHave_obj() <em>Have obj</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isHave_obj()
   * @generated
   * @ordered
   */
  protected boolean have_obj = HAVE_OBJ_EDEFAULT;

  /**
   * The cached value of the '{@link #getObjective() <em>Objective</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getObjective()
   * @generated
   * @ordered
   */
  protected Objective objective;

  /**
   * The default value of the '{@link #isHave_reach_obj() <em>Have reach obj</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isHave_reach_obj()
   * @generated
   * @ordered
   */
  protected static final boolean HAVE_REACH_OBJ_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isHave_reach_obj() <em>Have reach obj</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isHave_reach_obj()
   * @generated
   * @ordered
   */
  protected boolean have_reach_obj = HAVE_REACH_OBJ_EDEFAULT;

  /**
   * The cached value of the '{@link #getReachobjective() <em>Reachobjective</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReachobjective()
   * @generated
   * @ordered
   */
  protected ReachObjective reachobjective;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PuRSUEMLImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PursuemlPackage.Literals.PU_RSUEML;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Pdi> getLocations()
  {
    if (locations == null)
    {
      locations = new EObjectContainmentEList<Pdi>(Pdi.class, this, PursuemlPackage.PU_RSUEML__LOCATIONS);
    }
    return locations;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<connection> getConnections()
  {
    if (connections == null)
    {
      connections = new EObjectContainmentEList<connection>(connection.class, this, PursuemlPackage.PU_RSUEML__CONNECTIONS);
    }
    return connections;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Event> getEvents()
  {
    if (events == null)
    {
      events = new EObjectContainmentEList<Event>(Event.class, this, PursuemlPackage.PU_RSUEML__EVENTS);
    }
    return events;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Regola> getRegole()
  {
    if (regole == null)
    {
      regole = new EObjectContainmentEList<Regola>(Regola.class, this, PursuemlPackage.PU_RSUEML__REGOLE);
    }
    return regole;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Stato> getStati()
  {
    if (stati == null)
    {
      stati = new EObjectContainmentEList<Stato>(Stato.class, this, PursuemlPackage.PU_RSUEML__STATI);
    }
    return stati;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<StateDep> getDipendenze()
  {
    if (dipendenze == null)
    {
      dipendenze = new EObjectContainmentEList<StateDep>(StateDep.class, this, PursuemlPackage.PU_RSUEML__DIPENDENZE);
    }
    return dipendenze;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Agent> getAgents()
  {
    if (agents == null)
    {
      agents = new EObjectContainmentEList<Agent>(Agent.class, this, PursuemlPackage.PU_RSUEML__AGENTS);
    }
    return agents;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isHave_obj()
  {
    return have_obj;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setHave_obj(boolean newHave_obj)
  {
    boolean oldHave_obj = have_obj;
    have_obj = newHave_obj;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PursuemlPackage.PU_RSUEML__HAVE_OBJ, oldHave_obj, have_obj));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Objective getObjective()
  {
    return objective;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetObjective(Objective newObjective, NotificationChain msgs)
  {
    Objective oldObjective = objective;
    objective = newObjective;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PursuemlPackage.PU_RSUEML__OBJECTIVE, oldObjective, newObjective);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setObjective(Objective newObjective)
  {
    if (newObjective != objective)
    {
      NotificationChain msgs = null;
      if (objective != null)
        msgs = ((InternalEObject)objective).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PursuemlPackage.PU_RSUEML__OBJECTIVE, null, msgs);
      if (newObjective != null)
        msgs = ((InternalEObject)newObjective).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PursuemlPackage.PU_RSUEML__OBJECTIVE, null, msgs);
      msgs = basicSetObjective(newObjective, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PursuemlPackage.PU_RSUEML__OBJECTIVE, newObjective, newObjective));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isHave_reach_obj()
  {
    return have_reach_obj;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setHave_reach_obj(boolean newHave_reach_obj)
  {
    boolean oldHave_reach_obj = have_reach_obj;
    have_reach_obj = newHave_reach_obj;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PursuemlPackage.PU_RSUEML__HAVE_REACH_OBJ, oldHave_reach_obj, have_reach_obj));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ReachObjective getReachobjective()
  {
    return reachobjective;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetReachobjective(ReachObjective newReachobjective, NotificationChain msgs)
  {
    ReachObjective oldReachobjective = reachobjective;
    reachobjective = newReachobjective;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PursuemlPackage.PU_RSUEML__REACHOBJECTIVE, oldReachobjective, newReachobjective);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setReachobjective(ReachObjective newReachobjective)
  {
    if (newReachobjective != reachobjective)
    {
      NotificationChain msgs = null;
      if (reachobjective != null)
        msgs = ((InternalEObject)reachobjective).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PursuemlPackage.PU_RSUEML__REACHOBJECTIVE, null, msgs);
      if (newReachobjective != null)
        msgs = ((InternalEObject)newReachobjective).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PursuemlPackage.PU_RSUEML__REACHOBJECTIVE, null, msgs);
      msgs = basicSetReachobjective(newReachobjective, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PursuemlPackage.PU_RSUEML__REACHOBJECTIVE, newReachobjective, newReachobjective));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PursuemlPackage.PU_RSUEML__LOCATIONS:
        return ((InternalEList<?>)getLocations()).basicRemove(otherEnd, msgs);
      case PursuemlPackage.PU_RSUEML__CONNECTIONS:
        return ((InternalEList<?>)getConnections()).basicRemove(otherEnd, msgs);
      case PursuemlPackage.PU_RSUEML__EVENTS:
        return ((InternalEList<?>)getEvents()).basicRemove(otherEnd, msgs);
      case PursuemlPackage.PU_RSUEML__REGOLE:
        return ((InternalEList<?>)getRegole()).basicRemove(otherEnd, msgs);
      case PursuemlPackage.PU_RSUEML__STATI:
        return ((InternalEList<?>)getStati()).basicRemove(otherEnd, msgs);
      case PursuemlPackage.PU_RSUEML__DIPENDENZE:
        return ((InternalEList<?>)getDipendenze()).basicRemove(otherEnd, msgs);
      case PursuemlPackage.PU_RSUEML__AGENTS:
        return ((InternalEList<?>)getAgents()).basicRemove(otherEnd, msgs);
      case PursuemlPackage.PU_RSUEML__OBJECTIVE:
        return basicSetObjective(null, msgs);
      case PursuemlPackage.PU_RSUEML__REACHOBJECTIVE:
        return basicSetReachobjective(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PursuemlPackage.PU_RSUEML__LOCATIONS:
        return getLocations();
      case PursuemlPackage.PU_RSUEML__CONNECTIONS:
        return getConnections();
      case PursuemlPackage.PU_RSUEML__EVENTS:
        return getEvents();
      case PursuemlPackage.PU_RSUEML__REGOLE:
        return getRegole();
      case PursuemlPackage.PU_RSUEML__STATI:
        return getStati();
      case PursuemlPackage.PU_RSUEML__DIPENDENZE:
        return getDipendenze();
      case PursuemlPackage.PU_RSUEML__AGENTS:
        return getAgents();
      case PursuemlPackage.PU_RSUEML__HAVE_OBJ:
        return isHave_obj();
      case PursuemlPackage.PU_RSUEML__OBJECTIVE:
        return getObjective();
      case PursuemlPackage.PU_RSUEML__HAVE_REACH_OBJ:
        return isHave_reach_obj();
      case PursuemlPackage.PU_RSUEML__REACHOBJECTIVE:
        return getReachobjective();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PursuemlPackage.PU_RSUEML__LOCATIONS:
        getLocations().clear();
        getLocations().addAll((Collection<? extends Pdi>)newValue);
        return;
      case PursuemlPackage.PU_RSUEML__CONNECTIONS:
        getConnections().clear();
        getConnections().addAll((Collection<? extends connection>)newValue);
        return;
      case PursuemlPackage.PU_RSUEML__EVENTS:
        getEvents().clear();
        getEvents().addAll((Collection<? extends Event>)newValue);
        return;
      case PursuemlPackage.PU_RSUEML__REGOLE:
        getRegole().clear();
        getRegole().addAll((Collection<? extends Regola>)newValue);
        return;
      case PursuemlPackage.PU_RSUEML__STATI:
        getStati().clear();
        getStati().addAll((Collection<? extends Stato>)newValue);
        return;
      case PursuemlPackage.PU_RSUEML__DIPENDENZE:
        getDipendenze().clear();
        getDipendenze().addAll((Collection<? extends StateDep>)newValue);
        return;
      case PursuemlPackage.PU_RSUEML__AGENTS:
        getAgents().clear();
        getAgents().addAll((Collection<? extends Agent>)newValue);
        return;
      case PursuemlPackage.PU_RSUEML__HAVE_OBJ:
        setHave_obj((Boolean)newValue);
        return;
      case PursuemlPackage.PU_RSUEML__OBJECTIVE:
        setObjective((Objective)newValue);
        return;
      case PursuemlPackage.PU_RSUEML__HAVE_REACH_OBJ:
        setHave_reach_obj((Boolean)newValue);
        return;
      case PursuemlPackage.PU_RSUEML__REACHOBJECTIVE:
        setReachobjective((ReachObjective)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PursuemlPackage.PU_RSUEML__LOCATIONS:
        getLocations().clear();
        return;
      case PursuemlPackage.PU_RSUEML__CONNECTIONS:
        getConnections().clear();
        return;
      case PursuemlPackage.PU_RSUEML__EVENTS:
        getEvents().clear();
        return;
      case PursuemlPackage.PU_RSUEML__REGOLE:
        getRegole().clear();
        return;
      case PursuemlPackage.PU_RSUEML__STATI:
        getStati().clear();
        return;
      case PursuemlPackage.PU_RSUEML__DIPENDENZE:
        getDipendenze().clear();
        return;
      case PursuemlPackage.PU_RSUEML__AGENTS:
        getAgents().clear();
        return;
      case PursuemlPackage.PU_RSUEML__HAVE_OBJ:
        setHave_obj(HAVE_OBJ_EDEFAULT);
        return;
      case PursuemlPackage.PU_RSUEML__OBJECTIVE:
        setObjective((Objective)null);
        return;
      case PursuemlPackage.PU_RSUEML__HAVE_REACH_OBJ:
        setHave_reach_obj(HAVE_REACH_OBJ_EDEFAULT);
        return;
      case PursuemlPackage.PU_RSUEML__REACHOBJECTIVE:
        setReachobjective((ReachObjective)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PursuemlPackage.PU_RSUEML__LOCATIONS:
        return locations != null && !locations.isEmpty();
      case PursuemlPackage.PU_RSUEML__CONNECTIONS:
        return connections != null && !connections.isEmpty();
      case PursuemlPackage.PU_RSUEML__EVENTS:
        return events != null && !events.isEmpty();
      case PursuemlPackage.PU_RSUEML__REGOLE:
        return regole != null && !regole.isEmpty();
      case PursuemlPackage.PU_RSUEML__STATI:
        return stati != null && !stati.isEmpty();
      case PursuemlPackage.PU_RSUEML__DIPENDENZE:
        return dipendenze != null && !dipendenze.isEmpty();
      case PursuemlPackage.PU_RSUEML__AGENTS:
        return agents != null && !agents.isEmpty();
      case PursuemlPackage.PU_RSUEML__HAVE_OBJ:
        return have_obj != HAVE_OBJ_EDEFAULT;
      case PursuemlPackage.PU_RSUEML__OBJECTIVE:
        return objective != null;
      case PursuemlPackage.PU_RSUEML__HAVE_REACH_OBJ:
        return have_reach_obj != HAVE_REACH_OBJ_EDEFAULT;
      case PursuemlPackage.PU_RSUEML__REACHOBJECTIVE:
        return reachobjective != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (have_obj: ");
    result.append(have_obj);
    result.append(", have_reach_obj: ");
    result.append(have_reach_obj);
    result.append(')');
    return result.toString();
  }

} //PuRSUEMLImpl
