/*
 * generated by Xtext 2.17.0.M1
 */
package it.polimi.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class PuRSUEMLProposalProvider extends AbstractPuRSUEMLProposalProvider {
}
