/**
 * generated by Xtext 2.17.0.M1
 */
package it.polimi.pursueml;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see it.polimi.pursueml.PursuemlFactory
 * @model kind="package"
 * @generated
 */
public interface PursuemlPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "pursueml";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.it.polimi/pursueml";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "pursueml";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  PursuemlPackage eINSTANCE = it.polimi.pursueml.impl.PursuemlPackageImpl.init();

  /**
   * The meta object id for the '{@link it.polimi.pursueml.impl.PuRSUEMLImpl <em>Pu RSUEML</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see it.polimi.pursueml.impl.PuRSUEMLImpl
   * @see it.polimi.pursueml.impl.PursuemlPackageImpl#getPuRSUEML()
   * @generated
   */
  int PU_RSUEML = 0;

  /**
   * The feature id for the '<em><b>Locations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PU_RSUEML__LOCATIONS = 0;

  /**
   * The feature id for the '<em><b>Connections</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PU_RSUEML__CONNECTIONS = 1;

  /**
   * The feature id for the '<em><b>Events</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PU_RSUEML__EVENTS = 2;

  /**
   * The feature id for the '<em><b>Regole</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PU_RSUEML__REGOLE = 3;

  /**
   * The feature id for the '<em><b>Stati</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PU_RSUEML__STATI = 4;

  /**
   * The feature id for the '<em><b>Dipendenze</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PU_RSUEML__DIPENDENZE = 5;

  /**
   * The feature id for the '<em><b>Agents</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PU_RSUEML__AGENTS = 6;

  /**
   * The feature id for the '<em><b>Have obj</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PU_RSUEML__HAVE_OBJ = 7;

  /**
   * The feature id for the '<em><b>Objective</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PU_RSUEML__OBJECTIVE = 8;

  /**
   * The feature id for the '<em><b>Have reach obj</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PU_RSUEML__HAVE_REACH_OBJ = 9;

  /**
   * The feature id for the '<em><b>Reachobjective</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PU_RSUEML__REACHOBJECTIVE = 10;

  /**
   * The number of structural features of the '<em>Pu RSUEML</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PU_RSUEML_FEATURE_COUNT = 11;

  /**
   * The meta object id for the '{@link it.polimi.pursueml.impl.PdiImpl <em>Pdi</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see it.polimi.pursueml.impl.PdiImpl
   * @see it.polimi.pursueml.impl.PursuemlPackageImpl#getPdi()
   * @generated
   */
  int PDI = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PDI__NAME = 0;

  /**
   * The number of structural features of the '<em>Pdi</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PDI_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link it.polimi.pursueml.impl.connectionImpl <em>connection</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see it.polimi.pursueml.impl.connectionImpl
   * @see it.polimi.pursueml.impl.PursuemlPackageImpl#getconnection()
   * @generated
   */
  int CONNECTION = 2;

  /**
   * The feature id for the '<em><b>Pdi1</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECTION__PDI1 = 0;

  /**
   * The feature id for the '<em><b>Pdi2</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECTION__PDI2 = 1;

  /**
   * The feature id for the '<em><b>Distance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECTION__DISTANCE = 2;

  /**
   * The number of structural features of the '<em>connection</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECTION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link it.polimi.pursueml.impl.EventImpl <em>Event</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see it.polimi.pursueml.impl.EventImpl
   * @see it.polimi.pursueml.impl.PursuemlPackageImpl#getEvent()
   * @generated
   */
  int EVENT = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Collaborative</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__COLLABORATIVE = 1;

  /**
   * The feature id for the '<em><b>Location specific</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__LOCATION_SPECIFIC = 2;

  /**
   * The feature id for the '<em><b>Location</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__LOCATION = 3;

  /**
   * The feature id for the '<em><b>Has duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__HAS_DURATION = 4;

  /**
   * The feature id for the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__DURATION = 5;

  /**
   * The number of structural features of the '<em>Event</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link it.polimi.pursueml.impl.RegolaImpl <em>Regola</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see it.polimi.pursueml.impl.RegolaImpl
   * @see it.polimi.pursueml.impl.PursuemlPackageImpl#getRegola()
   * @generated
   */
  int REGOLA = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGOLA__NAME = 0;

  /**
   * The feature id for the '<em><b>First ev</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGOLA__FIRST_EV = 1;

  /**
   * The feature id for the '<em><b>Is seq1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGOLA__IS_SEQ1 = 2;

  /**
   * The feature id for the '<em><b>First seq</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGOLA__FIRST_SEQ = 3;

  /**
   * The feature id for the '<em><b>Then</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGOLA__THEN = 4;

  /**
   * The feature id for the '<em><b>Or</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGOLA__OR = 5;

  /**
   * The feature id for the '<em><b>Second ev</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGOLA__SECOND_EV = 6;

  /**
   * The feature id for the '<em><b>Is seq2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGOLA__IS_SEQ2 = 7;

  /**
   * The feature id for the '<em><b>Second seq</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGOLA__SECOND_SEQ = 8;

  /**
   * The number of structural features of the '<em>Regola</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGOLA_FEATURE_COUNT = 9;

  /**
   * The meta object id for the '{@link it.polimi.pursueml.impl.SequenceImpl <em>Sequence</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see it.polimi.pursueml.impl.SequenceImpl
   * @see it.polimi.pursueml.impl.PursuemlPackageImpl#getSequence()
   * @generated
   */
  int SEQUENCE = 5;

  /**
   * The feature id for the '<em><b>First ev</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEQUENCE__FIRST_EV = 0;

  /**
   * The feature id for the '<em><b>Is seq1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEQUENCE__IS_SEQ1 = 1;

  /**
   * The feature id for the '<em><b>First seq</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEQUENCE__FIRST_SEQ = 2;

  /**
   * The feature id for the '<em><b>Then</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEQUENCE__THEN = 3;

  /**
   * The feature id for the '<em><b>Or</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEQUENCE__OR = 4;

  /**
   * The feature id for the '<em><b>Second ev</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEQUENCE__SECOND_EV = 5;

  /**
   * The feature id for the '<em><b>Is seq2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEQUENCE__IS_SEQ2 = 6;

  /**
   * The feature id for the '<em><b>Second seq</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEQUENCE__SECOND_SEQ = 7;

  /**
   * The number of structural features of the '<em>Sequence</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEQUENCE_FEATURE_COUNT = 8;

  /**
   * The meta object id for the '{@link it.polimi.pursueml.impl.StatoImpl <em>Stato</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see it.polimi.pursueml.impl.StatoImpl
   * @see it.polimi.pursueml.impl.PursuemlPackageImpl#getStato()
   * @generated
   */
  int STATO = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATO__NAME = 0;

  /**
   * The feature id for the '<em><b>Tr</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATO__TR = 1;

  /**
   * The feature id for the '<em><b>Fl</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATO__FL = 2;

  /**
   * The feature id for the '<em><b>True events</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATO__TRUE_EVENTS = 3;

  /**
   * The feature id for the '<em><b>False events</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATO__FALSE_EVENTS = 4;

  /**
   * The number of structural features of the '<em>Stato</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATO_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link it.polimi.pursueml.impl.StateDepImpl <em>State Dep</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see it.polimi.pursueml.impl.StateDepImpl
   * @see it.polimi.pursueml.impl.PursuemlPackageImpl#getStateDep()
   * @generated
   */
  int STATE_DEP = 7;

  /**
   * The feature id for the '<em><b>Evento</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_DEP__EVENTO = 0;

  /**
   * The feature id for the '<em><b>Stat</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_DEP__STAT = 1;

  /**
   * The feature id for the '<em><b>Tr</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_DEP__TR = 2;

  /**
   * The feature id for the '<em><b>Fl</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_DEP__FL = 3;

  /**
   * The number of structural features of the '<em>State Dep</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_DEP_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link it.polimi.pursueml.impl.AgentImpl <em>Agent</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see it.polimi.pursueml.impl.AgentImpl
   * @see it.polimi.pursueml.impl.PursuemlPackageImpl#getAgent()
   * @generated
   */
  int AGENT = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Controllable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGENT__CONTROLLABLE = 1;

  /**
   * The feature id for the '<em><b>Mobile</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGENT__MOBILE = 2;

  /**
   * The feature id for the '<em><b>Speed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGENT__SPEED = 3;

  /**
   * The feature id for the '<em><b>Initial location</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGENT__INITIAL_LOCATION = 4;

  /**
   * The feature id for the '<em><b>Actions</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGENT__ACTIONS = 5;

  /**
   * The feature id for the '<em><b>Reactions</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGENT__REACTIONS = 6;

  /**
   * The number of structural features of the '<em>Agent</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGENT_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link it.polimi.pursueml.impl.ObjectiveImpl <em>Objective</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see it.polimi.pursueml.impl.ObjectiveImpl
   * @see it.polimi.pursueml.impl.PursuemlPackageImpl#getObjective()
   * @generated
   */
  int OBJECTIVE = 9;

  /**
   * The feature id for the '<em><b>Is if</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECTIVE__IS_IF = 0;

  /**
   * The feature id for the '<em><b>Cause</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECTIVE__CAUSE = 1;

  /**
   * The feature id for the '<em><b>Reaction</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECTIVE__REACTION = 2;

  /**
   * The feature id for the '<em><b>Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECTIVE__TIME = 3;

  /**
   * The feature id for the '<em><b>Is avoid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECTIVE__IS_AVOID = 4;

  /**
   * The feature id for the '<em><b>Lose</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECTIVE__LOSE = 5;

  /**
   * The number of structural features of the '<em>Objective</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECTIVE_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link it.polimi.pursueml.impl.ReachObjectiveImpl <em>Reach Objective</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see it.polimi.pursueml.impl.ReachObjectiveImpl
   * @see it.polimi.pursueml.impl.PursuemlPackageImpl#getReachObjective()
   * @generated
   */
  int REACH_OBJECTIVE = 10;

  /**
   * The feature id for the '<em><b>Goal</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REACH_OBJECTIVE__GOAL = 0;

  /**
   * The feature id for the '<em><b>Life span</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REACH_OBJECTIVE__LIFE_SPAN = 1;

  /**
   * The number of structural features of the '<em>Reach Objective</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REACH_OBJECTIVE_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link it.polimi.pursueml.PuRSUEML <em>Pu RSUEML</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pu RSUEML</em>'.
   * @see it.polimi.pursueml.PuRSUEML
   * @generated
   */
  EClass getPuRSUEML();

  /**
   * Returns the meta object for the containment reference list '{@link it.polimi.pursueml.PuRSUEML#getLocations <em>Locations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Locations</em>'.
   * @see it.polimi.pursueml.PuRSUEML#getLocations()
   * @see #getPuRSUEML()
   * @generated
   */
  EReference getPuRSUEML_Locations();

  /**
   * Returns the meta object for the containment reference list '{@link it.polimi.pursueml.PuRSUEML#getConnections <em>Connections</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Connections</em>'.
   * @see it.polimi.pursueml.PuRSUEML#getConnections()
   * @see #getPuRSUEML()
   * @generated
   */
  EReference getPuRSUEML_Connections();

  /**
   * Returns the meta object for the containment reference list '{@link it.polimi.pursueml.PuRSUEML#getEvents <em>Events</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Events</em>'.
   * @see it.polimi.pursueml.PuRSUEML#getEvents()
   * @see #getPuRSUEML()
   * @generated
   */
  EReference getPuRSUEML_Events();

  /**
   * Returns the meta object for the containment reference list '{@link it.polimi.pursueml.PuRSUEML#getRegole <em>Regole</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Regole</em>'.
   * @see it.polimi.pursueml.PuRSUEML#getRegole()
   * @see #getPuRSUEML()
   * @generated
   */
  EReference getPuRSUEML_Regole();

  /**
   * Returns the meta object for the containment reference list '{@link it.polimi.pursueml.PuRSUEML#getStati <em>Stati</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Stati</em>'.
   * @see it.polimi.pursueml.PuRSUEML#getStati()
   * @see #getPuRSUEML()
   * @generated
   */
  EReference getPuRSUEML_Stati();

  /**
   * Returns the meta object for the containment reference list '{@link it.polimi.pursueml.PuRSUEML#getDipendenze <em>Dipendenze</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Dipendenze</em>'.
   * @see it.polimi.pursueml.PuRSUEML#getDipendenze()
   * @see #getPuRSUEML()
   * @generated
   */
  EReference getPuRSUEML_Dipendenze();

  /**
   * Returns the meta object for the containment reference list '{@link it.polimi.pursueml.PuRSUEML#getAgents <em>Agents</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Agents</em>'.
   * @see it.polimi.pursueml.PuRSUEML#getAgents()
   * @see #getPuRSUEML()
   * @generated
   */
  EReference getPuRSUEML_Agents();

  /**
   * Returns the meta object for the attribute '{@link it.polimi.pursueml.PuRSUEML#isHave_obj <em>Have obj</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Have obj</em>'.
   * @see it.polimi.pursueml.PuRSUEML#isHave_obj()
   * @see #getPuRSUEML()
   * @generated
   */
  EAttribute getPuRSUEML_Have_obj();

  /**
   * Returns the meta object for the containment reference '{@link it.polimi.pursueml.PuRSUEML#getObjective <em>Objective</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Objective</em>'.
   * @see it.polimi.pursueml.PuRSUEML#getObjective()
   * @see #getPuRSUEML()
   * @generated
   */
  EReference getPuRSUEML_Objective();

  /**
   * Returns the meta object for the attribute '{@link it.polimi.pursueml.PuRSUEML#isHave_reach_obj <em>Have reach obj</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Have reach obj</em>'.
   * @see it.polimi.pursueml.PuRSUEML#isHave_reach_obj()
   * @see #getPuRSUEML()
   * @generated
   */
  EAttribute getPuRSUEML_Have_reach_obj();

  /**
   * Returns the meta object for the containment reference '{@link it.polimi.pursueml.PuRSUEML#getReachobjective <em>Reachobjective</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Reachobjective</em>'.
   * @see it.polimi.pursueml.PuRSUEML#getReachobjective()
   * @see #getPuRSUEML()
   * @generated
   */
  EReference getPuRSUEML_Reachobjective();

  /**
   * Returns the meta object for class '{@link it.polimi.pursueml.Pdi <em>Pdi</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pdi</em>'.
   * @see it.polimi.pursueml.Pdi
   * @generated
   */
  EClass getPdi();

  /**
   * Returns the meta object for the attribute '{@link it.polimi.pursueml.Pdi#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see it.polimi.pursueml.Pdi#getName()
   * @see #getPdi()
   * @generated
   */
  EAttribute getPdi_Name();

  /**
   * Returns the meta object for class '{@link it.polimi.pursueml.connection <em>connection</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>connection</em>'.
   * @see it.polimi.pursueml.connection
   * @generated
   */
  EClass getconnection();

  /**
   * Returns the meta object for the reference '{@link it.polimi.pursueml.connection#getPdi1 <em>Pdi1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Pdi1</em>'.
   * @see it.polimi.pursueml.connection#getPdi1()
   * @see #getconnection()
   * @generated
   */
  EReference getconnection_Pdi1();

  /**
   * Returns the meta object for the reference '{@link it.polimi.pursueml.connection#getPdi2 <em>Pdi2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Pdi2</em>'.
   * @see it.polimi.pursueml.connection#getPdi2()
   * @see #getconnection()
   * @generated
   */
  EReference getconnection_Pdi2();

  /**
   * Returns the meta object for the attribute '{@link it.polimi.pursueml.connection#getDistance <em>Distance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Distance</em>'.
   * @see it.polimi.pursueml.connection#getDistance()
   * @see #getconnection()
   * @generated
   */
  EAttribute getconnection_Distance();

  /**
   * Returns the meta object for class '{@link it.polimi.pursueml.Event <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Event</em>'.
   * @see it.polimi.pursueml.Event
   * @generated
   */
  EClass getEvent();

  /**
   * Returns the meta object for the attribute '{@link it.polimi.pursueml.Event#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see it.polimi.pursueml.Event#getName()
   * @see #getEvent()
   * @generated
   */
  EAttribute getEvent_Name();

  /**
   * Returns the meta object for the attribute '{@link it.polimi.pursueml.Event#isCollaborative <em>Collaborative</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Collaborative</em>'.
   * @see it.polimi.pursueml.Event#isCollaborative()
   * @see #getEvent()
   * @generated
   */
  EAttribute getEvent_Collaborative();

  /**
   * Returns the meta object for the attribute '{@link it.polimi.pursueml.Event#isLocation_specific <em>Location specific</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Location specific</em>'.
   * @see it.polimi.pursueml.Event#isLocation_specific()
   * @see #getEvent()
   * @generated
   */
  EAttribute getEvent_Location_specific();

  /**
   * Returns the meta object for the reference '{@link it.polimi.pursueml.Event#getLocation <em>Location</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Location</em>'.
   * @see it.polimi.pursueml.Event#getLocation()
   * @see #getEvent()
   * @generated
   */
  EReference getEvent_Location();

  /**
   * Returns the meta object for the attribute '{@link it.polimi.pursueml.Event#isHas_duration <em>Has duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Has duration</em>'.
   * @see it.polimi.pursueml.Event#isHas_duration()
   * @see #getEvent()
   * @generated
   */
  EAttribute getEvent_Has_duration();

  /**
   * Returns the meta object for the attribute '{@link it.polimi.pursueml.Event#getDuration <em>Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Duration</em>'.
   * @see it.polimi.pursueml.Event#getDuration()
   * @see #getEvent()
   * @generated
   */
  EAttribute getEvent_Duration();

  /**
   * Returns the meta object for class '{@link it.polimi.pursueml.Regola <em>Regola</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Regola</em>'.
   * @see it.polimi.pursueml.Regola
   * @generated
   */
  EClass getRegola();

  /**
   * Returns the meta object for the attribute '{@link it.polimi.pursueml.Regola#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see it.polimi.pursueml.Regola#getName()
   * @see #getRegola()
   * @generated
   */
  EAttribute getRegola_Name();

  /**
   * Returns the meta object for the reference '{@link it.polimi.pursueml.Regola#getFirst_ev <em>First ev</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>First ev</em>'.
   * @see it.polimi.pursueml.Regola#getFirst_ev()
   * @see #getRegola()
   * @generated
   */
  EReference getRegola_First_ev();

  /**
   * Returns the meta object for the attribute '{@link it.polimi.pursueml.Regola#isIs_seq1 <em>Is seq1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Is seq1</em>'.
   * @see it.polimi.pursueml.Regola#isIs_seq1()
   * @see #getRegola()
   * @generated
   */
  EAttribute getRegola_Is_seq1();

  /**
   * Returns the meta object for the containment reference '{@link it.polimi.pursueml.Regola#getFirst_seq <em>First seq</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>First seq</em>'.
   * @see it.polimi.pursueml.Regola#getFirst_seq()
   * @see #getRegola()
   * @generated
   */
  EReference getRegola_First_seq();

  /**
   * Returns the meta object for the attribute '{@link it.polimi.pursueml.Regola#isThen <em>Then</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Then</em>'.
   * @see it.polimi.pursueml.Regola#isThen()
   * @see #getRegola()
   * @generated
   */
  EAttribute getRegola_Then();

  /**
   * Returns the meta object for the attribute '{@link it.polimi.pursueml.Regola#isOr <em>Or</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Or</em>'.
   * @see it.polimi.pursueml.Regola#isOr()
   * @see #getRegola()
   * @generated
   */
  EAttribute getRegola_Or();

  /**
   * Returns the meta object for the reference '{@link it.polimi.pursueml.Regola#getSecond_ev <em>Second ev</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Second ev</em>'.
   * @see it.polimi.pursueml.Regola#getSecond_ev()
   * @see #getRegola()
   * @generated
   */
  EReference getRegola_Second_ev();

  /**
   * Returns the meta object for the attribute '{@link it.polimi.pursueml.Regola#isIs_seq2 <em>Is seq2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Is seq2</em>'.
   * @see it.polimi.pursueml.Regola#isIs_seq2()
   * @see #getRegola()
   * @generated
   */
  EAttribute getRegola_Is_seq2();

  /**
   * Returns the meta object for the containment reference '{@link it.polimi.pursueml.Regola#getSecond_seq <em>Second seq</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Second seq</em>'.
   * @see it.polimi.pursueml.Regola#getSecond_seq()
   * @see #getRegola()
   * @generated
   */
  EReference getRegola_Second_seq();

  /**
   * Returns the meta object for class '{@link it.polimi.pursueml.Sequence <em>Sequence</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sequence</em>'.
   * @see it.polimi.pursueml.Sequence
   * @generated
   */
  EClass getSequence();

  /**
   * Returns the meta object for the reference '{@link it.polimi.pursueml.Sequence#getFirst_ev <em>First ev</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>First ev</em>'.
   * @see it.polimi.pursueml.Sequence#getFirst_ev()
   * @see #getSequence()
   * @generated
   */
  EReference getSequence_First_ev();

  /**
   * Returns the meta object for the attribute '{@link it.polimi.pursueml.Sequence#isIs_seq1 <em>Is seq1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Is seq1</em>'.
   * @see it.polimi.pursueml.Sequence#isIs_seq1()
   * @see #getSequence()
   * @generated
   */
  EAttribute getSequence_Is_seq1();

  /**
   * Returns the meta object for the containment reference '{@link it.polimi.pursueml.Sequence#getFirst_seq <em>First seq</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>First seq</em>'.
   * @see it.polimi.pursueml.Sequence#getFirst_seq()
   * @see #getSequence()
   * @generated
   */
  EReference getSequence_First_seq();

  /**
   * Returns the meta object for the attribute '{@link it.polimi.pursueml.Sequence#isThen <em>Then</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Then</em>'.
   * @see it.polimi.pursueml.Sequence#isThen()
   * @see #getSequence()
   * @generated
   */
  EAttribute getSequence_Then();

  /**
   * Returns the meta object for the attribute '{@link it.polimi.pursueml.Sequence#isOr <em>Or</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Or</em>'.
   * @see it.polimi.pursueml.Sequence#isOr()
   * @see #getSequence()
   * @generated
   */
  EAttribute getSequence_Or();

  /**
   * Returns the meta object for the reference '{@link it.polimi.pursueml.Sequence#getSecond_ev <em>Second ev</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Second ev</em>'.
   * @see it.polimi.pursueml.Sequence#getSecond_ev()
   * @see #getSequence()
   * @generated
   */
  EReference getSequence_Second_ev();

  /**
   * Returns the meta object for the attribute '{@link it.polimi.pursueml.Sequence#isIs_seq2 <em>Is seq2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Is seq2</em>'.
   * @see it.polimi.pursueml.Sequence#isIs_seq2()
   * @see #getSequence()
   * @generated
   */
  EAttribute getSequence_Is_seq2();

  /**
   * Returns the meta object for the containment reference '{@link it.polimi.pursueml.Sequence#getSecond_seq <em>Second seq</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Second seq</em>'.
   * @see it.polimi.pursueml.Sequence#getSecond_seq()
   * @see #getSequence()
   * @generated
   */
  EReference getSequence_Second_seq();

  /**
   * Returns the meta object for class '{@link it.polimi.pursueml.Stato <em>Stato</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Stato</em>'.
   * @see it.polimi.pursueml.Stato
   * @generated
   */
  EClass getStato();

  /**
   * Returns the meta object for the attribute '{@link it.polimi.pursueml.Stato#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see it.polimi.pursueml.Stato#getName()
   * @see #getStato()
   * @generated
   */
  EAttribute getStato_Name();

  /**
   * Returns the meta object for the attribute '{@link it.polimi.pursueml.Stato#isTr <em>Tr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tr</em>'.
   * @see it.polimi.pursueml.Stato#isTr()
   * @see #getStato()
   * @generated
   */
  EAttribute getStato_Tr();

  /**
   * Returns the meta object for the attribute '{@link it.polimi.pursueml.Stato#isFl <em>Fl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Fl</em>'.
   * @see it.polimi.pursueml.Stato#isFl()
   * @see #getStato()
   * @generated
   */
  EAttribute getStato_Fl();

  /**
   * Returns the meta object for the reference list '{@link it.polimi.pursueml.Stato#getTrue_events <em>True events</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>True events</em>'.
   * @see it.polimi.pursueml.Stato#getTrue_events()
   * @see #getStato()
   * @generated
   */
  EReference getStato_True_events();

  /**
   * Returns the meta object for the reference list '{@link it.polimi.pursueml.Stato#getFalse_events <em>False events</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>False events</em>'.
   * @see it.polimi.pursueml.Stato#getFalse_events()
   * @see #getStato()
   * @generated
   */
  EReference getStato_False_events();

  /**
   * Returns the meta object for class '{@link it.polimi.pursueml.StateDep <em>State Dep</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>State Dep</em>'.
   * @see it.polimi.pursueml.StateDep
   * @generated
   */
  EClass getStateDep();

  /**
   * Returns the meta object for the reference '{@link it.polimi.pursueml.StateDep#getEvento <em>Evento</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Evento</em>'.
   * @see it.polimi.pursueml.StateDep#getEvento()
   * @see #getStateDep()
   * @generated
   */
  EReference getStateDep_Evento();

  /**
   * Returns the meta object for the reference '{@link it.polimi.pursueml.StateDep#getStat <em>Stat</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Stat</em>'.
   * @see it.polimi.pursueml.StateDep#getStat()
   * @see #getStateDep()
   * @generated
   */
  EReference getStateDep_Stat();

  /**
   * Returns the meta object for the attribute '{@link it.polimi.pursueml.StateDep#isTr <em>Tr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tr</em>'.
   * @see it.polimi.pursueml.StateDep#isTr()
   * @see #getStateDep()
   * @generated
   */
  EAttribute getStateDep_Tr();

  /**
   * Returns the meta object for the attribute '{@link it.polimi.pursueml.StateDep#isFl <em>Fl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Fl</em>'.
   * @see it.polimi.pursueml.StateDep#isFl()
   * @see #getStateDep()
   * @generated
   */
  EAttribute getStateDep_Fl();

  /**
   * Returns the meta object for class '{@link it.polimi.pursueml.Agent <em>Agent</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Agent</em>'.
   * @see it.polimi.pursueml.Agent
   * @generated
   */
  EClass getAgent();

  /**
   * Returns the meta object for the attribute '{@link it.polimi.pursueml.Agent#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see it.polimi.pursueml.Agent#getName()
   * @see #getAgent()
   * @generated
   */
  EAttribute getAgent_Name();

  /**
   * Returns the meta object for the attribute '{@link it.polimi.pursueml.Agent#isControllable <em>Controllable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Controllable</em>'.
   * @see it.polimi.pursueml.Agent#isControllable()
   * @see #getAgent()
   * @generated
   */
  EAttribute getAgent_Controllable();

  /**
   * Returns the meta object for the attribute '{@link it.polimi.pursueml.Agent#isMobile <em>Mobile</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Mobile</em>'.
   * @see it.polimi.pursueml.Agent#isMobile()
   * @see #getAgent()
   * @generated
   */
  EAttribute getAgent_Mobile();

  /**
   * Returns the meta object for the attribute '{@link it.polimi.pursueml.Agent#getSpeed <em>Speed</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Speed</em>'.
   * @see it.polimi.pursueml.Agent#getSpeed()
   * @see #getAgent()
   * @generated
   */
  EAttribute getAgent_Speed();

  /**
   * Returns the meta object for the reference '{@link it.polimi.pursueml.Agent#getInitial_location <em>Initial location</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Initial location</em>'.
   * @see it.polimi.pursueml.Agent#getInitial_location()
   * @see #getAgent()
   * @generated
   */
  EReference getAgent_Initial_location();

  /**
   * Returns the meta object for the reference list '{@link it.polimi.pursueml.Agent#getActions <em>Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Actions</em>'.
   * @see it.polimi.pursueml.Agent#getActions()
   * @see #getAgent()
   * @generated
   */
  EReference getAgent_Actions();

  /**
   * Returns the meta object for the reference list '{@link it.polimi.pursueml.Agent#getReactions <em>Reactions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Reactions</em>'.
   * @see it.polimi.pursueml.Agent#getReactions()
   * @see #getAgent()
   * @generated
   */
  EReference getAgent_Reactions();

  /**
   * Returns the meta object for class '{@link it.polimi.pursueml.Objective <em>Objective</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Objective</em>'.
   * @see it.polimi.pursueml.Objective
   * @generated
   */
  EClass getObjective();

  /**
   * Returns the meta object for the attribute '{@link it.polimi.pursueml.Objective#isIs_if <em>Is if</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Is if</em>'.
   * @see it.polimi.pursueml.Objective#isIs_if()
   * @see #getObjective()
   * @generated
   */
  EAttribute getObjective_Is_if();

  /**
   * Returns the meta object for the reference '{@link it.polimi.pursueml.Objective#getCause <em>Cause</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Cause</em>'.
   * @see it.polimi.pursueml.Objective#getCause()
   * @see #getObjective()
   * @generated
   */
  EReference getObjective_Cause();

  /**
   * Returns the meta object for the reference '{@link it.polimi.pursueml.Objective#getReaction <em>Reaction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Reaction</em>'.
   * @see it.polimi.pursueml.Objective#getReaction()
   * @see #getObjective()
   * @generated
   */
  EReference getObjective_Reaction();

  /**
   * Returns the meta object for the attribute '{@link it.polimi.pursueml.Objective#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Time</em>'.
   * @see it.polimi.pursueml.Objective#getTime()
   * @see #getObjective()
   * @generated
   */
  EAttribute getObjective_Time();

  /**
   * Returns the meta object for the attribute '{@link it.polimi.pursueml.Objective#isIs_avoid <em>Is avoid</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Is avoid</em>'.
   * @see it.polimi.pursueml.Objective#isIs_avoid()
   * @see #getObjective()
   * @generated
   */
  EAttribute getObjective_Is_avoid();

  /**
   * Returns the meta object for the reference '{@link it.polimi.pursueml.Objective#getLose <em>Lose</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Lose</em>'.
   * @see it.polimi.pursueml.Objective#getLose()
   * @see #getObjective()
   * @generated
   */
  EReference getObjective_Lose();

  /**
   * Returns the meta object for class '{@link it.polimi.pursueml.ReachObjective <em>Reach Objective</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Reach Objective</em>'.
   * @see it.polimi.pursueml.ReachObjective
   * @generated
   */
  EClass getReachObjective();

  /**
   * Returns the meta object for the reference '{@link it.polimi.pursueml.ReachObjective#getGoal <em>Goal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Goal</em>'.
   * @see it.polimi.pursueml.ReachObjective#getGoal()
   * @see #getReachObjective()
   * @generated
   */
  EReference getReachObjective_Goal();

  /**
   * Returns the meta object for the attribute '{@link it.polimi.pursueml.ReachObjective#getLife_span <em>Life span</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Life span</em>'.
   * @see it.polimi.pursueml.ReachObjective#getLife_span()
   * @see #getReachObjective()
   * @generated
   */
  EAttribute getReachObjective_Life_span();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  PursuemlFactory getPursuemlFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link it.polimi.pursueml.impl.PuRSUEMLImpl <em>Pu RSUEML</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see it.polimi.pursueml.impl.PuRSUEMLImpl
     * @see it.polimi.pursueml.impl.PursuemlPackageImpl#getPuRSUEML()
     * @generated
     */
    EClass PU_RSUEML = eINSTANCE.getPuRSUEML();

    /**
     * The meta object literal for the '<em><b>Locations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PU_RSUEML__LOCATIONS = eINSTANCE.getPuRSUEML_Locations();

    /**
     * The meta object literal for the '<em><b>Connections</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PU_RSUEML__CONNECTIONS = eINSTANCE.getPuRSUEML_Connections();

    /**
     * The meta object literal for the '<em><b>Events</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PU_RSUEML__EVENTS = eINSTANCE.getPuRSUEML_Events();

    /**
     * The meta object literal for the '<em><b>Regole</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PU_RSUEML__REGOLE = eINSTANCE.getPuRSUEML_Regole();

    /**
     * The meta object literal for the '<em><b>Stati</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PU_RSUEML__STATI = eINSTANCE.getPuRSUEML_Stati();

    /**
     * The meta object literal for the '<em><b>Dipendenze</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PU_RSUEML__DIPENDENZE = eINSTANCE.getPuRSUEML_Dipendenze();

    /**
     * The meta object literal for the '<em><b>Agents</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PU_RSUEML__AGENTS = eINSTANCE.getPuRSUEML_Agents();

    /**
     * The meta object literal for the '<em><b>Have obj</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PU_RSUEML__HAVE_OBJ = eINSTANCE.getPuRSUEML_Have_obj();

    /**
     * The meta object literal for the '<em><b>Objective</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PU_RSUEML__OBJECTIVE = eINSTANCE.getPuRSUEML_Objective();

    /**
     * The meta object literal for the '<em><b>Have reach obj</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PU_RSUEML__HAVE_REACH_OBJ = eINSTANCE.getPuRSUEML_Have_reach_obj();

    /**
     * The meta object literal for the '<em><b>Reachobjective</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PU_RSUEML__REACHOBJECTIVE = eINSTANCE.getPuRSUEML_Reachobjective();

    /**
     * The meta object literal for the '{@link it.polimi.pursueml.impl.PdiImpl <em>Pdi</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see it.polimi.pursueml.impl.PdiImpl
     * @see it.polimi.pursueml.impl.PursuemlPackageImpl#getPdi()
     * @generated
     */
    EClass PDI = eINSTANCE.getPdi();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PDI__NAME = eINSTANCE.getPdi_Name();

    /**
     * The meta object literal for the '{@link it.polimi.pursueml.impl.connectionImpl <em>connection</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see it.polimi.pursueml.impl.connectionImpl
     * @see it.polimi.pursueml.impl.PursuemlPackageImpl#getconnection()
     * @generated
     */
    EClass CONNECTION = eINSTANCE.getconnection();

    /**
     * The meta object literal for the '<em><b>Pdi1</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONNECTION__PDI1 = eINSTANCE.getconnection_Pdi1();

    /**
     * The meta object literal for the '<em><b>Pdi2</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONNECTION__PDI2 = eINSTANCE.getconnection_Pdi2();

    /**
     * The meta object literal for the '<em><b>Distance</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONNECTION__DISTANCE = eINSTANCE.getconnection_Distance();

    /**
     * The meta object literal for the '{@link it.polimi.pursueml.impl.EventImpl <em>Event</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see it.polimi.pursueml.impl.EventImpl
     * @see it.polimi.pursueml.impl.PursuemlPackageImpl#getEvent()
     * @generated
     */
    EClass EVENT = eINSTANCE.getEvent();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__NAME = eINSTANCE.getEvent_Name();

    /**
     * The meta object literal for the '<em><b>Collaborative</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__COLLABORATIVE = eINSTANCE.getEvent_Collaborative();

    /**
     * The meta object literal for the '<em><b>Location specific</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__LOCATION_SPECIFIC = eINSTANCE.getEvent_Location_specific();

    /**
     * The meta object literal for the '<em><b>Location</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EVENT__LOCATION = eINSTANCE.getEvent_Location();

    /**
     * The meta object literal for the '<em><b>Has duration</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__HAS_DURATION = eINSTANCE.getEvent_Has_duration();

    /**
     * The meta object literal for the '<em><b>Duration</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__DURATION = eINSTANCE.getEvent_Duration();

    /**
     * The meta object literal for the '{@link it.polimi.pursueml.impl.RegolaImpl <em>Regola</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see it.polimi.pursueml.impl.RegolaImpl
     * @see it.polimi.pursueml.impl.PursuemlPackageImpl#getRegola()
     * @generated
     */
    EClass REGOLA = eINSTANCE.getRegola();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REGOLA__NAME = eINSTANCE.getRegola_Name();

    /**
     * The meta object literal for the '<em><b>First ev</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REGOLA__FIRST_EV = eINSTANCE.getRegola_First_ev();

    /**
     * The meta object literal for the '<em><b>Is seq1</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REGOLA__IS_SEQ1 = eINSTANCE.getRegola_Is_seq1();

    /**
     * The meta object literal for the '<em><b>First seq</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REGOLA__FIRST_SEQ = eINSTANCE.getRegola_First_seq();

    /**
     * The meta object literal for the '<em><b>Then</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REGOLA__THEN = eINSTANCE.getRegola_Then();

    /**
     * The meta object literal for the '<em><b>Or</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REGOLA__OR = eINSTANCE.getRegola_Or();

    /**
     * The meta object literal for the '<em><b>Second ev</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REGOLA__SECOND_EV = eINSTANCE.getRegola_Second_ev();

    /**
     * The meta object literal for the '<em><b>Is seq2</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REGOLA__IS_SEQ2 = eINSTANCE.getRegola_Is_seq2();

    /**
     * The meta object literal for the '<em><b>Second seq</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REGOLA__SECOND_SEQ = eINSTANCE.getRegola_Second_seq();

    /**
     * The meta object literal for the '{@link it.polimi.pursueml.impl.SequenceImpl <em>Sequence</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see it.polimi.pursueml.impl.SequenceImpl
     * @see it.polimi.pursueml.impl.PursuemlPackageImpl#getSequence()
     * @generated
     */
    EClass SEQUENCE = eINSTANCE.getSequence();

    /**
     * The meta object literal for the '<em><b>First ev</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SEQUENCE__FIRST_EV = eINSTANCE.getSequence_First_ev();

    /**
     * The meta object literal for the '<em><b>Is seq1</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SEQUENCE__IS_SEQ1 = eINSTANCE.getSequence_Is_seq1();

    /**
     * The meta object literal for the '<em><b>First seq</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SEQUENCE__FIRST_SEQ = eINSTANCE.getSequence_First_seq();

    /**
     * The meta object literal for the '<em><b>Then</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SEQUENCE__THEN = eINSTANCE.getSequence_Then();

    /**
     * The meta object literal for the '<em><b>Or</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SEQUENCE__OR = eINSTANCE.getSequence_Or();

    /**
     * The meta object literal for the '<em><b>Second ev</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SEQUENCE__SECOND_EV = eINSTANCE.getSequence_Second_ev();

    /**
     * The meta object literal for the '<em><b>Is seq2</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SEQUENCE__IS_SEQ2 = eINSTANCE.getSequence_Is_seq2();

    /**
     * The meta object literal for the '<em><b>Second seq</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SEQUENCE__SECOND_SEQ = eINSTANCE.getSequence_Second_seq();

    /**
     * The meta object literal for the '{@link it.polimi.pursueml.impl.StatoImpl <em>Stato</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see it.polimi.pursueml.impl.StatoImpl
     * @see it.polimi.pursueml.impl.PursuemlPackageImpl#getStato()
     * @generated
     */
    EClass STATO = eINSTANCE.getStato();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATO__NAME = eINSTANCE.getStato_Name();

    /**
     * The meta object literal for the '<em><b>Tr</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATO__TR = eINSTANCE.getStato_Tr();

    /**
     * The meta object literal for the '<em><b>Fl</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATO__FL = eINSTANCE.getStato_Fl();

    /**
     * The meta object literal for the '<em><b>True events</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATO__TRUE_EVENTS = eINSTANCE.getStato_True_events();

    /**
     * The meta object literal for the '<em><b>False events</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATO__FALSE_EVENTS = eINSTANCE.getStato_False_events();

    /**
     * The meta object literal for the '{@link it.polimi.pursueml.impl.StateDepImpl <em>State Dep</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see it.polimi.pursueml.impl.StateDepImpl
     * @see it.polimi.pursueml.impl.PursuemlPackageImpl#getStateDep()
     * @generated
     */
    EClass STATE_DEP = eINSTANCE.getStateDep();

    /**
     * The meta object literal for the '<em><b>Evento</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE_DEP__EVENTO = eINSTANCE.getStateDep_Evento();

    /**
     * The meta object literal for the '<em><b>Stat</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE_DEP__STAT = eINSTANCE.getStateDep_Stat();

    /**
     * The meta object literal for the '<em><b>Tr</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATE_DEP__TR = eINSTANCE.getStateDep_Tr();

    /**
     * The meta object literal for the '<em><b>Fl</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATE_DEP__FL = eINSTANCE.getStateDep_Fl();

    /**
     * The meta object literal for the '{@link it.polimi.pursueml.impl.AgentImpl <em>Agent</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see it.polimi.pursueml.impl.AgentImpl
     * @see it.polimi.pursueml.impl.PursuemlPackageImpl#getAgent()
     * @generated
     */
    EClass AGENT = eINSTANCE.getAgent();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AGENT__NAME = eINSTANCE.getAgent_Name();

    /**
     * The meta object literal for the '<em><b>Controllable</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AGENT__CONTROLLABLE = eINSTANCE.getAgent_Controllable();

    /**
     * The meta object literal for the '<em><b>Mobile</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AGENT__MOBILE = eINSTANCE.getAgent_Mobile();

    /**
     * The meta object literal for the '<em><b>Speed</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AGENT__SPEED = eINSTANCE.getAgent_Speed();

    /**
     * The meta object literal for the '<em><b>Initial location</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AGENT__INITIAL_LOCATION = eINSTANCE.getAgent_Initial_location();

    /**
     * The meta object literal for the '<em><b>Actions</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AGENT__ACTIONS = eINSTANCE.getAgent_Actions();

    /**
     * The meta object literal for the '<em><b>Reactions</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AGENT__REACTIONS = eINSTANCE.getAgent_Reactions();

    /**
     * The meta object literal for the '{@link it.polimi.pursueml.impl.ObjectiveImpl <em>Objective</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see it.polimi.pursueml.impl.ObjectiveImpl
     * @see it.polimi.pursueml.impl.PursuemlPackageImpl#getObjective()
     * @generated
     */
    EClass OBJECTIVE = eINSTANCE.getObjective();

    /**
     * The meta object literal for the '<em><b>Is if</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJECTIVE__IS_IF = eINSTANCE.getObjective_Is_if();

    /**
     * The meta object literal for the '<em><b>Cause</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJECTIVE__CAUSE = eINSTANCE.getObjective_Cause();

    /**
     * The meta object literal for the '<em><b>Reaction</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJECTIVE__REACTION = eINSTANCE.getObjective_Reaction();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJECTIVE__TIME = eINSTANCE.getObjective_Time();

    /**
     * The meta object literal for the '<em><b>Is avoid</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJECTIVE__IS_AVOID = eINSTANCE.getObjective_Is_avoid();

    /**
     * The meta object literal for the '<em><b>Lose</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJECTIVE__LOSE = eINSTANCE.getObjective_Lose();

    /**
     * The meta object literal for the '{@link it.polimi.pursueml.impl.ReachObjectiveImpl <em>Reach Objective</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see it.polimi.pursueml.impl.ReachObjectiveImpl
     * @see it.polimi.pursueml.impl.PursuemlPackageImpl#getReachObjective()
     * @generated
     */
    EClass REACH_OBJECTIVE = eINSTANCE.getReachObjective();

    /**
     * The meta object literal for the '<em><b>Goal</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REACH_OBJECTIVE__GOAL = eINSTANCE.getReachObjective_Goal();

    /**
     * The meta object literal for the '<em><b>Life span</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REACH_OBJECTIVE__LIFE_SPAN = eINSTANCE.getReachObjective_Life_span();

  }

} //PursuemlPackage
