/**
 * generated by Xtext 2.17.0.M1
 */
package it.polimi.pursueml;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Reach Objective</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.polimi.pursueml.ReachObjective#getGoal <em>Goal</em>}</li>
 *   <li>{@link it.polimi.pursueml.ReachObjective#getLife_span <em>Life span</em>}</li>
 * </ul>
 *
 * @see it.polimi.pursueml.PursuemlPackage#getReachObjective()
 * @model
 * @generated
 */
public interface ReachObjective extends EObject
{
  /**
   * Returns the value of the '<em><b>Goal</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Goal</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Goal</em>' reference.
   * @see #setGoal(Event)
   * @see it.polimi.pursueml.PursuemlPackage#getReachObjective_Goal()
   * @model
   * @generated
   */
  Event getGoal();

  /**
   * Sets the value of the '{@link it.polimi.pursueml.ReachObjective#getGoal <em>Goal</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Goal</em>' reference.
   * @see #getGoal()
   * @generated
   */
  void setGoal(Event value);

  /**
   * Returns the value of the '<em><b>Life span</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Life span</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Life span</em>' attribute.
   * @see #setLife_span(int)
   * @see it.polimi.pursueml.PursuemlPackage#getReachObjective_Life_span()
   * @model
   * @generated
   */
  int getLife_span();

  /**
   * Sets the value of the '{@link it.polimi.pursueml.ReachObjective#getLife_span <em>Life span</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Life span</em>' attribute.
   * @see #getLife_span()
   * @generated
   */
  void setLife_span(int value);

} // ReachObjective
