/*
 * generated by Xtext 2.17.0.M1
 */
package it.polimi.ui.tests;

import com.google.inject.Injector;
import it.polimi.pursueml.ui.internal.PursuemlActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class PuRSUEMLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return PursuemlActivator.getInstance().getInjector("it.polimi.PuRSUEML");
	}

}
